// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhexbumarwqpmzzexnqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZXhidW1hcndxcG16emV4bnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDUzNjgsImV4cCI6MjA2OTM4MTM2OH0.vmDbcHGoadDLTJj-6ijJqsoH06UtpJ-6KMWnejgfBCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});